// user
export const REHYDRATE_ACCESS_TOKEN = 'REHYDRATE_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

export const GET_INVESTMENTS = 'GET_INVESTMENTS';
export const GET_INVESTMENTS_SUCCEEDED = 'GET_INVESTMENTS_SUCCEEDED';
export const GET_INVESTMENTS_FAILED = 'GET_INVESTMENTS_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCEEDED = 'GET_USER_SUCCEEDED';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCEEDED = 'SIGN_UP_SUCCEEDED';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const AUTH = 'AUTH';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCEEDED = 'VERIFY_EMAIL_SUCCEEDED';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';
